### ISSUE TITLE
Getting started page says I can use bower, but bower claims package cannot be found...

### ISSUE THREAD

**Issue by palodequeso** [ocadotechnology/hexagonjs#1]
https://www.hexagonjs.io/guide/getting-started/

says that I can use ```bower install hexagon-js```

but when I run it, I get

```bower                        ENOTFOUND Package hexagon-js not found```

:cry:

**Comment by jmsmyth** [comment]
@palodequeso I think we added the bower install instructions a bit prematurely, sorry about that :-(. 

Anyway, installing with bower should be all set up now.

**Comment by palodequeso** [comment]
Many thanks! I'll have a go fairly soon!
