### ISSUE TITLE
Picker: should add the hx-btn class to the node supplied in the constructor

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#108]
In particular, the result of `hx.picker` doesn't have the class (but I think it would make more sense to do it in `hx.Picker` not `hx.picker` because the user should not care)

**Comment by jmsmyth** [comment]
+1

It might also make sense for hx.Picker to check that the selector passed in is for a button element

**Comment by c-frater** [comment]
Had a look at this, I'm not sure it does make sense for hx.Picker to check the selector as you can use `hx-btn` on non-button elements (e.g. span, div etc)
