### ISSUE TITLE
Add hx.Selection::warning, hx.Selection::action etc

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#109]
Methods to add `hx-warning` etc and remove all the other context classes.

This is useful in the fluid API:

    `hx.picker().warning()`
    `hx.button().warning()`

**Comment by c-frater** [comment]
Palette already has an api for applying the context to an element, I'm not sure if adding it to the selection as well makes sense

```
hx.palette.context(hx.picker(), 'warning')
hx.palette.context(hx.button(), 'warning')
```

**Comment by jmsmyth** [comment]
Yeah, I don't think these belong in the selection api. 

Going to close this for now - if the palette functions turn out to be too awkward to use, we can revisit
