### ISSUE TITLE
Color Picker: setting values with the api does not fire any events

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#113]
The usual component change event has a cause field with "user" and "api". However programatically changing the color picker doesn't seem to trigger the change or changeend events.

Consider:

```
hx.select('body').add(hx.colorPicker().attr('id', 'apiEvents').classed('hx-btn', true))
hx.component(apiEvents).on('change', (p) => console.log(p)).on('changeend', (p) => console.log(p)).value('#ddd')
```

Nothing is logged.

**Comment by c-frater** [comment]
I'd expect it to fire the `change` event with the cause of `api`. 
This might be a 2.0.0 change as the events currently emit the color and not an event in the format of 
```js
{
  cause: 'user',
  value: ...
}
```

**Comment by c-frater** [comment]
Closing as we are removing the colour picker module in #454
