### ISSUE TITLE
Color Picker: hx.colorPicker should add the hx-btn class in the constructor, and allow the button text as a constructor option

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#114]
Similar to #108 

Color Picker is a bit odd with the fluid api.

```
 hx.select('body').add(hx.colorPicker().classed('hx-btn', true).text('Cool color picker'))
```

Really hx-btn should be added in the constructor (it isn't really a valid color picker without it) and it would also make more sense if the button text were a constructor option with a sensible default.

```
hx.select('body').add(hx.colorPicker({text: 'Cool color picker'}))
```

**Comment by c-frater** [comment]
This is a different issue than that of #108 as the color picker doesn't do anything with the element it's applied to. As a result, this doesn't affect `hx.ColorPicker` as you should be able to add a color picker to any element (same as dropdown) and only affects the fluid api version of color pickers.

**Comment by c-frater** [comment]
Closing as we are removing the colour picker module in #454
