### ISSUE TITLE
DateTimePicker: should be possible to set the range option like DatePicker

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#120]
EG to show a period over which to draw a graph.

**Comment by c-frater** [comment]
This makes sense, however, in terms of UX it would be the equivalent of having 2 date/time pickers next to each other. It might be worth just having an example that demonstrates how to make a date/time range picker, rather than adding it as a feature of the Hexagon library

**Comment by c-frater** [comment]
Upon review, I don't think it would be sensible to be able to pass the range into the date time picker due to the nature of the split between Date and Time.
Apps that need to use a date/time range should use two separate DateTimePickers.
