### ISSUE TITLE
Preferences: "Timezone" in hexagon is not timezone, it's UTC Offset

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#129]
The current "timezone" in hexagon isn't the timezone at all, it's the UTC offset.
This means that in timezones where there is Daylight Savings, the user will have to change the timezone when clocks go back/forward, which is confusing and annoying.

Instead, the dropdown should have options from tzdata, like "Europe/London", or maybe a more user-friendly equivalent.

EG here is how gnome's time zone picker does it -
![screenshot from 2016-02-03 09 54 35](https://cloud.githubusercontent.com/assets/7927477/12778732/46ccd36a-ca5c-11e5-95ce-3f54fff783bc.png)

**Comment by c-frater** [comment]
Adding this option is entirely up to the user. Hexagon does not store this data as it is a large overhead.
If you wish to use a timezone by name, you can provide a list of timezones using `hx.preferences.supportedTimezones` and also set a `timezoneOffsetLookup` to get the offset from the provided list of timezones.

**Comment by c-frater** [comment]
It's probably worth having an example with a selection of tzdata used as the timezones to demonstrate this capability.

**Comment by c-frater** [comment]
https://github.com/ocadotechnology/hexagonjs-site/issues/72
