### ISSUE TITLE
Add in hx.version for identifying which version of Hexagon is loaded

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#131]
This should be part of the compile script that generates the hexagon header
It should be added after the line that declares `window.hx`as a variable.

The following should suffice:

```
'hx.version = "' + version + '";',
```

**Comment by jmsmyth** [comment]
Also, a test should be added to ensure it doesn't disappear again without being noticed :)

**Comment by c-frater** [comment]
Makes sense - not sure where the test should go though as it's not added by any particular module...
Theoretically it can go inside any module as it is added to the start of every build

**Comment by jmsmyth** [comment]
This has been done in the webpack branch
