### ISSUE TITLE
Plot: add an option to disable automatic graph redraw when the containing element is resized

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#152]

**Comment by georgesimms** [comment]
When would this be useful?

**Comment by jmsmyth** [comment]
@georgesimms In the cases where resize events don't work (apparently there are some?), managing the redraws yourself might be needed. 

Or, if you already know when the graph container is resized for some reason, you may want to turn off automatic redraws on resize, and handle it yourself.

Also, some graphs could be a fixed size (like sparklines), and so it would make sense to not add the resize event handler in this case

**Comment by c-frater** [comment]
Flexbox sometimes causes issues with the resize events not being fired, depending on the layout used.
