### ISSUE TITLE
Number Picker: disable the decrement/increment buttons when the value is at the min/max

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#159]
This involves adding/removing the disabled attribute to the buttons when the value changes - currently the buttons just ignore input when they hit the limits

**Comment by c-frater** [comment]
Duplicate of #150 ?

**Comment by jmsmyth** [comment]
Slightly different - I've added more of a description

**Comment by c-frater** [comment]
Makes sense now :)
