### ISSUE TITLE
New Component: Tooltip

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#16]

**Comment by c-frater** [comment]
Had a look at this and it might make more sense to have an option for dropdowns to target/follow the mouse instead of creating an entirely new module? It would mean removing the 'slide' animation when it's following the mouse and instead just having a fade-in. 
I think this one is worth a discussion @jmsmyth :)

**Comment by jmsmyth** [comment]
Do you think tooltip needs to follow the mouse?

**Comment by c-frater** [comment]
I think it's one of those things that we _kind of_ already do, it depends on how it's implemented really.
Either we use hx-dropdown and it behaves like a dropdown or it becomes a completely new module that behaves differently. 
It probably makes the most sense to just use dropdown, especially as it already has 'string' content handling, in which case the follow the mouse functionality probably doesn't make sense. It also probably doesn't make sense to have it's own module when it's essentially just a dropdown with some extra styles...

**Comment by sjpayling** [comment]
Follow up with @jmsmyth  for details

**Comment by c-frater** [comment]
Followed up with James - The current api is missing a 'remove' method which should be trivial to add. I'm hoping to get this included in the 1.4 release.

**Comment by c-frater** [comment]
After some thought/discussion with @jmsmyth, we came to the conclusion that it would make more sense to use a new API for the tooltip.

It should be possible to:
- define the text used for the tooltip
- position based on the mouse cursor
- position based on a selector
- remove the tooltip
- use the tooltip for desktop and mobile devices (mouse/touch)

Additional functionality could include:
- the ability to add spacing between the 'target' and the tooltip
- the ability to have the tooltip follow the mouse

It may be possible to share the positioning logic with the Dropdown module, in which case it may make sense to have the positioning logic as a separate/exposed module for positioning things?

**Comment by c-frater** [comment]
Resolved in #551
