### ISSUE TITLE
Modal: hx.modal.dialog : it is not possible to tell when the modal is visible to the user

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#160]
It is true that hx.modal.dialog accepts a callback that is fired when the user clicks on a button. But this is a different problem. In particular, when you call hx.modal.dialog, the dialog is not immediately visible. There is no callback called when the modal becomes visible either. This makes it difficult to test interactions using modals.

**Comment by c-frater** [comment]
hx.modal.dialog returns a modal, as such you can use the events emitted by it:
```js
hx.modal.dialog('Modal Warning Example', 'You did something that caused a warning.', function (val) {}, {
  titleClass: 'warning',
  icon: 'fa fa-warning'
}).on('showend', function(a) { console.log('I'm Showing')})
```

**Comment by georgesimms** [comment]
thanks
