### ISSUE TITLE
EventEmitter: memory leak when many unique namespaces are used

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#179]
When removing a handler from an event emitter the underlying BasicEventEmitter reference is held onto, even when it contains no handlers. When removing handlers, check what can be cleaned up to avoid memory leaks.

This is a problem when many generated unique namespaces are used, as over time it gathers up more and more BasicEventEmitters.

**Comment by c-frater** [comment]
As a related note, Dropdowns (and other things using click detectors) could add the click detector listeners only when they are needed, in the case of dropdowns it would be when they are opened.
Click detectors should probably not be used without some degree of cleanup (be it removing the event or actually calling `cleanUp`) from the module using them.
