### ISSUE TITLE
All: User-facing text should be configurable

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#18]
It should be possible to define the text used by hexagon when creating elements (such as 'Sort By' and the default form validation messages) to enable the localisation of text

**Comment by georgesimms** [comment]
I've been thinking about this one a bit more. How would you all feel about The ability to supply text for multiple locales?

Something like

      hx.userFacingText('noData', {en: 'No data', fr: 'Aucunes données'})

The getter would then check the current locale using the preferences module and fetch the appropriate text accordingly.

There are some issues here - there needs to be well defined behavior in the case where the string is not defined for the current locale (console warning and fall back to English?)

Also this would break getter-setter symmetry, which might be a bit awkward.
