### ISSUE TITLE
Dropdown: improve reusability of dropdowns

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#180]
Current dropdowns are difficult to reuse reliably. It would be nice to have the ability to change the setup function and manually call render 'on the fly'
This would involve adding:
```js
hx.Dropdown::render([callback: Function]) // Render the dropdown using the current renderer (without closing/opening)
hx.Dropdown::setupDropdown(content) // Set the dropdown content
hx.Dropdown::setupDropdown() // Get the current dropdown content
```
This would need to deal with the fact that the dropdown content can be a string or a function.
Also, setting the 'setupDropdown' function whilst the dropdown is open should also potentially call render

**Comment by georgesimms** [comment]
Would the idea here to be to render in a detached div, and then just add it to the dom when show is called ?

**Comment by c-frater** [comment]
This issue is mainly for re-rendering the dropdown when it's already open and less about reusing the actual selection. 
It might cause a lot of overhead to render dropdowns before they are needed (e.g. if you have 500 dropdowns on the page, you don't want to store all the rendered content in the detached dom if you're not going to open them)

**Comment by georgesimms** [comment]
Right, so render shouldn't do anything if the dropdown isn't open yet ?

**Comment by c-frater** [comment]
The use case for this is in `Autocomplete Picker`:

We want to be able to re-render the dropdown without having to do this:

```coffeescript
renderMenu = (items) ->
        menu.items(items)
        menu.dropdown._.setupDropdown(menu.dropdown._.dropdown.node())
```

**Comment by georgesimms** [comment]
Right
