### ISSUE TITLE
Animation: Add facility to repeat a morph

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#192]
Something like

```
const repeatMorph = (selector, morphSetup) => morphSetup(hx.select(selector).morph()).then(() => repeatMorph(selector, morphSetup)).go()
repeatMorph('body', (morph) => morph.thenStyle('background-color', '#ff0000', 1000).thenStyle('background-color', '#00ff00', 1000).thenStyle('background-color', '#0000ff', 1000))
```

Not sure if this is the way to go, it creates a new morph each time - is this efficient ? Would it be better to reuse the old morph ?

**Comment by c-frater** [comment]
It looks like the code creates a new Morph every time `then` or `and` is called anyway so I this is probably fine.
You could probably to use `hx.morph.register` to 'save' the morph under a name (this is how 'expand', 'fadeout' etc. in the Morphs module are made) and then use it that way (i.e. `.morph().with('customMorph').go()`) although if you have multiple different morphs I think your repeatMorph looks sensible enough. Is that about right @jmsmyth?
