### ISSUE TITLE
Palette: add 'disabled' as a context

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#195]
The current palette functions have an array of contexts to use for text/background/context which currently do not include `disabled` which, for most modules (including palette with `hx-background-disabled`), is a valid class. 

Should this be added as a context in the array of valid contexts?

Example:
```js
hx.palette.context(element, 'disabled')
hx.palette.backgroundContext(element, 'disabled')
```

**Comment by georgesimms** [comment]
Also, it should probably make a console warning if you do a rubbish context like

```
hx.palette.context('.hx-btn', 'rubbish')
```

At the moment it just silently fails

**Comment by jonthans** [comment]
+1

**Comment by c-frater** [comment]
It looks like we have the console warning for invalid classes already so that part is done - we just need to add the `disabled` class

**Comment by jmsmyth** [comment]
Added in 1.7.0
