### ISSUE TITLE
Form Builder / Tag Input: validator behaves oddly for tag inputs in forms

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#203]
```js
const tagInput = hexagon.tagInput({
  validator: (term) => 'bob'
})

const formSel = hexagon.detached('div')

void new hexagon.Form(formSel.node())
  .addTagInput('Tag Input', {
    tagInputOptions: {
      validator: (term) => 'bob'
    }
  })
  .addSubmit('Submit')

const bodySel = hexagon.select('body')
bodySel.append(tagInput)
bodySel.append(formSel)
```

In the first case, pressing enter shows the validation error.

In the second case, pressing enter doesn't show any validation error, it just refuses to create a tag and shows a thick black box around the tag input.

(The error will show if you press the submit button of the whole form, but this is rather counterintuitive).

**Comment by c-frater** [comment]
I'm pretty sure I fixed the 'black box' bit in #197 as I noticed it in passing (and it was caused by a style specificity issue)
I think the other issue is due to how browsers deal with nested forms as the tag-input has it's own internal form.
