### ISSUE TITLE
User Facing Text: convert all modules to use new user facing text module

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#211]
TODO:
- [x] autocomplete
- [x] data-table
- [x] file-input
- [x] form
- [x] picker
- [x] plot
- [x] preferences
- [x] tag-input

**Comment by c-frater** [comment]
The date localizer module does have pre-defined text but it's probably worth refactoring as part of #234 as the fact that it is static at the moment isn't great.

**Comment by sjpayling** [comment]
Needs documentation
