### ISSUE TITLE
FileInput: hx.FileInput::value returns an array, even when multiple is set to false

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#212]
This is counterintuitive

**Comment by c-frater** [comment]
The logic behind this is because the input value returned is a `FileList` regardless of length which must be iterated over

**Comment by georgesimms** [comment]
Is it possible to check whether multiple is true, and if not, just pull out the first one any way ?

**Comment by c-frater** [comment]
It's easy to do, I was more pointing out that it would be moving away from the inbuilt input behaviour which, in this case, doesn't actually make sense anyway as it's converted to an array.

**Comment by c-frater** [comment]
After some thought, this module is working in the correct way. It mirrors the functionality of the inbuilt file input and is already non-standard compared to other Hexagon modules in that the `value` method is not circular (i.e. you can't set, only clear the value for security reasons).
