### ISSUE TITLE
Internet Explorer: Menu displays incorrectly

### ISSUE THREAD

**Issue by luis-carrasco** [ocadotechnology/hexagonjs#227]
![0853669e-0bcf-11e6-8f90-29e0fe2e66dd](https://cloud.githubusercontent.com/assets/3194349/14825084/62244af2-0bd0-11e6-8b82-910c276551d6.JPG)

We use hexagon to display our menus. Any IE user, when clicking on them, they display at the bottom left corner.

Browser: Internet Explorer 11 (11.0.9600)

**Comment by c-frater** [comment]
@luis-carrasco If you could include the version(s) of IE this affects and what version of Hexagon you're using that would be great :)

**Comment by luis-carrasco** [comment]
hexagon version 1.0.3
