### ISSUE TITLE
Selection: it should be possible to aggregate selections

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#230]
If I have an array of selections it should be possible to convert it into a multiselection.

Something like

```
hx.aggregateSelections = (selections) => hx.selectAll(hx.flatten(selections.map((selection) => selection.nodes)))
```

If you wanted to be more Object oriented you could

```
class Selection {
  union(that) {
    return hx.selectAll([...this.nodes, ...that.nodes])
  }
}
```

(Although the nodes property on selection isn't documented)

Why would I want to do that, and what advantages does this have over just using the View module ?

Well now that we are supposed to be doing fluid things, I might want to

```
const createBla = (name) => hx.detached('div').class('bla').text(name)
const data = [1, 2, 3]
const ret = hx.detached('div').add(hx.aggregateSelections(data.map(createBla)))
```

Alternatively I could

```
const ret = hx.detached('div')
data.map(createBla).forEach((sel) => ret.add(sel))
ret
```

But that is a bit more awkward.

Also the View module doesn't work very well with detached elements - you are expected to mutate dom elements passed into the enter / update functions

**Comment by c-frater** [comment]
Just looking at your example, you can already do:
```js
const createBla = (name) => hx.detached('div').class('bla').text(name)
const data = [1, 2, 3]
const ret = hx.detached('div').add(data.map(createBla))
```

or:

``js
const createBla = (name) => hx.detached('div').class('bla').text(name).node()
const data = [1, 2, 3]
const elems = hx.selectAll(data.map(createBla))
const ret = hx.detached('div').add(elems)
```

I may have missed something but I think that resolves this issue?
