### ISSUE TITLE
Date Localizer: investigate use of the internationalisation api for the default localizer

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#234]
The `Intl` api provides a lot of functionality that the default date localizer could use to prevent it being stuck in 'English' mode.
This relies heavily on the support for the `Intl` library but could involve requiring the intl module

**Comment by georgesimms** [comment]
+1

**Comment by c-frater** [comment]
Completed in 2.1.0 (#532)

Worth noting - This is supported in the latest browsers and the polyfill(s) don't seem to support timezones currently so worth checking [MDN - Intl.DateTimeFormat - Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Browser_compatibility) if you intend to use this.
