### ISSUE TITLE
Fluid: There should be a better way of creating a button anchor using the fluid api.

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#237]
Eg through an href option to hx.button

```
function hx.button (options) {
  const button = options.href
    ? hx.detached('a').attr('href', options.href)
    : hx.detached('btn')
  return button.class('hx-btn')
}

```

**Comment by c-frater** [comment]
The above example doesn't deal with the context class option, the below would be a suitable alternative:
```coffeescript
hx.button = (options = {}) -> 
  button = if options.href
    hx.detached('a').attr('href', options.href)
  else 
    hx.detached('button').attr('type', 'button')

  hx.palette.context(button.class('hx-btn'), options.context)
```
https://github.com/ocadotechnology/hexagonjs/blob/master/modules/fluid/main/index.coffee#L14

**Comment by jmsmyth** [comment]
`hx.button` behaviour has changed a bit in the webpack branch - it now acts like the other browser-provided components, where the first argument is the class, so this change would only survive for the rest of the version 1.x.x series of releases.

With button standardized to match the other things like `hx.div()` and `hx.span()`, the new way would be something like this
```
hx.a('hx-btn').attr('href', '#link')
hx.button('hx-btn')
```

So I'll close this for now - we might want to later add an options object for hx.div/span/button/etc for applying context classes and attributes to the elements when they are created
