### ISSUE TITLE
hx.notify styles bug

### ISSUE THREAD

**Issue by DarthVanger** [ocadotechnology/hexagonjs#280]
Hexagon version: 1.4.2    

Notifications generated by hx.notify have incorrect layout, because the `flex-wrap: nowrap` style for `.hx-notification`

https://github.com/ocadotechnology/hexagonjs/blob/1.4.2/modules/notify/main/index.scss#L50

gets overridden by `.hx-horizontal`'s `flex-flow: row wrap;`.    

So the `.hx-notification` element ends up having `flex-wrap: wrap`, which causes icons and text to be on separate rows.

See the plunker:
https://plnkr.co/edit/TalyJxcI2TNhrKJIMgqa?p=preview

Screenshot:
![hx-notify-layout-bug](https://cloud.githubusercontent.com/assets/6686679/17370284/1e03c718-59a4-11e6-9423-b7fad3c553ba.jpg)

P.S. on the same plunkr you can see that using 'cssclass' option makes sucess/error icons disappear, which I guess is another bug...

**Comment by jmsmyth** [comment]
Great bug report! This makes it super clear what needs fixing
