### ISSUE TITLE
Add ability to set the scrolling of a selection

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#289]
Something like

```
class Selection {
  function horizontalScroll (newScroll) {
    if (arguments.length) {
      const clampedScroll = hx.clamp(0, 1, newScroll)
      this.nodes.forEach((node) => node.scrollLeft = node.scrollWidth * clampedScroll)
   } else {
      return this.nodes.map((node) => {
        const scroll = node.scrollWidth && (node.scrollLeft / node.scrollWidth)
        return hx.clamp(0, 1, scroll)
      })
   }
}
```

And the same for vertical (except replace scrollLeft with scrollTop and scrollWidth with scrollHeight)

**Comment by jmsmyth** [comment]
I think this might be outside of the scope of selection, which we've tried to keep the api surface for as small as possible. 

We could add a utility for doing this, but it feels a bit niche?

**Comment by georgesimms** [comment]
I don't mind if you want to close this as a won't fix (we already have code to do this).

**Comment by c-frater** [comment]
I'm not sure it's worth adding a util method for this - There aren't many situations where I can see it being used without it being something quite bespoke to start with. 
Marked as wontfix and closed
