### ISSUE TITLE
Animate: add option to globally disable animations

### ISSUE THREAD

**Issue by jonthans** [ocadotechnology/hexagonjs#297]
Currently, it is not possible to disable animation e.g. for testing.
It would be helpful to have the ability to disable animations globally.

**Comment by georgesimms** [comment]
@jonthans why?

**Comment by jonthans** [comment]
Uff, that was 7 months ago. I'm sure there was a reason back then and since no one seems to have deemed it necessary since then I'm sure this is not an issue anymore.
