### ISSUE TITLE
Allow HTML content inside notification

### ISSUE THREAD

**Issue by Tomasz-Zlamaniec** [ocadotechnology/hexagonjs#299]
Allow custom HTML content inside notification OR allow more properties than just text.

For example with notification's header, main text, and footer we could write:
`hx.notify.warning({header:"Abc", content:"Abc", footer:"Abc"});`
to get this result
![image](https://cloud.githubusercontent.com/assets/20813116/18205290/27fead1e-7119-11e6-8f01-258845d01281.png)

**Comment by c-frater** [comment]
I think the best method of solving this would be to add the ability to pass a `content` function through instead of a message (in a similar way to how the `Dropdown` module currently works)

Something like:
```js
hx.notify.warning({message: 'Test...'}, {
   renderer: (data, node) => hx.select(node).text(data.message)
})
```
