### ISSUE TITLE
Travis: configure so that releases happen automatically when tags are pushed

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#30]

**Comment by jmsmyth** [comment]
We now have it where it publishes to npm automatically when tagged on master - the dist folder still has to be built manually, but this could also be built in travis, so will leave this open for now

**Comment by c-frater** [comment]
This was completed in *2.0.0*. Travis now builds the `dist` folder as part of the publish job run when tagging
