### ISSUE TITLE
Sticky Table Headers: disappearing column headers for nested data tables

### ISSUE THREAD

**Issue by dawidchodura** [ocadotechnology/hexagonjs#302]
Hexagon version: 1.3.2 (all themes)
Expected: When the data table contains another data table as a collapsibleRenderer, the column headers on the outer table should not disappear after selecting different "rows per page" value.
Actual: The column headers sometimes disappear.

The issue is caused by the process in which the header nodes are selected in sticky-table-headers. When the data tables are nested, there are many nodes matching ".hx-sticky-table-header-top", ".hx-sticky-table-header-left", ".hx-sticky-table-header-top-left" to choose from. The non-determinisitc behaviour is caused by different document order in different cases. The invocation of "select" returns the first element found (first element in document order), which sometimes belongs to the outer table node and sometimes to the inner table node.

Replacing "select" invocations with the "shallowSelect" fixes the issue (added in #104).

**Comment by jmsmyth** [comment]
Fixed in 1.7.0
