### ISSUE TITLE
Crumbtrail: don't use .html

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#308]
Otherwise an xss attack is possible if you are dynamically creating the separator from something supplied by the user.

This will involve changing this line to use https://github.com/ocadotechnology/hexagonjs/blob/master/modules/crumbtrail/main/index.coffee#L20 `.text` instead of `.html`

**Comment by avi-jain** [comment]
Hullo,
I'm new to contributions and have sent a pr with the change mentioned above.
Thanks

**Comment by jmsmyth** [comment]
Thanks for the PR :)
