### ISSUE TITLE
Crumbtrail: Setting hx-crumbtrail class on node

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#310]
Should the crumbtrail node already have this class before the constructor is called ? The docs seem to suggest so. If so, hx.crumbtrail should set it. However if so we might want to push it down into the Crumbtrail constructor as it's a bit non-standard to do it this way around.

**Comment by jmsmyth** [comment]
This will involve adding a line that adds the `'hx-crumbtrail'` class to the element passed into the constructor for Crumbtrail. The place to do that is here: https://github.com/ocadotechnology/hexagonjs/blob/master/modules/crumbtrail/main/index.coffee#L6

To add the class you'll need to add something like

    hx.select(@selector).classed('hx-crumbtrail', true)
