### ISSUE TITLE
Tag Input: invalid tag entered when using autocomplete

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#313]
When using a tag input with autocomplete enabled, it is possible to enter tags incorrectly by _clicking_ the value in the autocomplete, as opposed to using the keyboard.

Example:
```js
var autocompleteData = [
  'bob',
  'steve',
  'dave'
]

hx.select('body').clear()
  .add(hx.tagInput({
    autocompleteData: autocompleteData
  }))
```
- type `b`
- click `bob` entry (must click, entering using the keyboard works fine)
- `b` tag is entered, along with `bob` tag

I think this is because the `blur` event causes the text entered to be added as a tag and then the autocomplete selected value is also added as a tag afterwards. This should be resolvable by either disabling the `blur` event when autocomplete is enabled or by adding handling to detect when an autocomplete item has been selected and not add the manually entered text.

**Comment by jonthans** [comment]
Not sure what the listening on `blur` is actually doing at that point? If I take it out entirely, the behaviour seems to stay the same for the normal tag-input as well?

**Comment by c-frater** [comment]
Blur is there so that when you leave the tag input it tries to enter the text. 
This is a UX decision made when the tag input was first implemented as some users were unaware as to why it wasn't working - they had entered text but not pressed 'enter' and then expected it to do something.
It should retain the `blur` action and deal with the combination of the this and the menu setter.
