### ISSUE TITLE
Autocomplete Picker: Value setter does not work

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#332]
On https://www.hexagonjs.io/docs/autocomplete-picker/  : 

    hx.select('#autocompletePicker-externalMatch').component().value() // => undefined
    hx.select('#autocompletePicker-externalMatch').component().value({county: 'London', name: 'Old Street'}, (data) => console.log(data)) // => logs `{county: 'London', name: 'Moorgate'}` and sets the Picker to "Moorgate London"

It does seem to validate the picker is being set to a valid value, but regardless of what that value is, the result is always the same

**Comment by c-frater** [comment]
It looks like the reason that particular autocomplete picker is failing is because it doesn't have a `valueLookup` defined. This ends up returning all the results internally when searching for the value provided in `value` and then using the first one (which in this case, is London Moorgate)
