### ISSUE TITLE
Autocompete: Adds the first item in the list (even if it doesn't match the current filter) when you type really quick then hit enter

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#346]
## Context
Typing enter before the debounce duration completes allows values to be entered which don't match the current filter (if you are fast enough)

## Expected Behaviour
Autocomplete should not allow you to enter any values whilst loading (this includes the debounce period)

## Possible Fix
I'll submit a PR

## Steps to Reproduce
1. Go to https://www.hexagonjs.io/docs/autocomplete-picker/
2. In the first autocomplete example type 'c', followed immediately by <enter>
3. The autocomplete will close and will have the value 'a' (it should be 'c')

**Comment by c-frater** [comment]
Nice catch - If this affects the regular autocomplete as well then it's probably more of a reason to update it to use the new feed (#338)
