### ISSUE TITLE
DatePicker: validRange should be a constructor parameter

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#350]
DatePicker: validRange should be a constructor parameter

## Context
This is to make it easy to set the validRange from the fluid API, as well as from DateTimePicker

## Expected Behavior
```
hx.datePicker({validRange: {start, end}}).component().validRange().should.equal({start, end})
```

## Actual Behavior
```
hx.datePicker({validRange: {start, end}}).component().validRange().should.equal({start: undefined, end: undefined})
```

## Possible Fix
Accept validRange as a constructor parameter

## Your Environment

* Hexagon Version: 1.8.2
* Browser Name and version: Chromium 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04

* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by c-frater** [comment]
Marked as bug - all values with a setter/getter should be available as constructor options
