### ISSUE TITLE
DataTable: when updating a filter programatically an input box was not updated

### ISSUE THREAD

**Issue by jsuchenia** [ocadotechnology/hexagonjs#352]
DataTable: when updating a filter programatically an input box was not updated

## Context
When updating a simple filter field (as an option `filter` during construction) an input box was not updated

## Expected Behavior
Filter input box should contains a search term

## Actual Behavior
Filter input box doesn't contain a search term

## Possible Fix
Update input element in our code - but it's a hack

## Steps to Reproduce
Link provided on chat

## Your Environment
* Hexagon Version: 1.8.2
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): MacOX

**Comment by llichota** [comment]
Also, after applying filter, when moving to next pagination page the filter no longer applies (on second and further page there are entries that should be filtered out)
