### ISSUE TITLE
Plot: axis labels should never overlap

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#353]
## Context

Creating a bar chart with interval labels (1AM - 2AM) for 24 hours causes overlapping labels in most cases as there isn't enough room to display all the text correctly.

## Expected Behavior

Graphs with lots of axis tick values (e.g. bar charts) should not allow overlapping of tick values.

In general, it should never be possible for labels to overlap.

## Actual Behavior

Currently, most graphs handle this using the scale, however for discrete axes we seem to always use _all_ the labels.

**Comment by jmsmyth** [comment]
For linear scales you can avoid this by setting the `tickSpacing` property. Or there is the `nthTickVisible` option if you have discrete scales.

But, I'd agree it would be nice for graphs to do this automatically.
