### ISSUE TITLE
DataTable: filter ignored when sorting any column in descending order

### ISSUE THREAD

**Issue by pkubowicz** [ocadotechnology/hexagonjs#360]
## Context
Users complain that my data table 'loses' filter when they sort data

## Expected Behavior
Filter applies, only matching rows appear

## Actual Behavior
All rows are visible

## Steps to Reproduce
1. Open https://www.hexagonjs.io/docs/1.9.0/data-table/
2. In the first example type '41' to the filter field (you should see 2 of 3 rows)
3. Click any column 2 times to sort it in descending order

If the demo page works correct, the regression was introduced after version 1.4.2.

## Your Environment
* Hexagon Version: 1.9.0
* Browser Name and version: Chrome 55.0.2883.87 (64-bit) - also reproduced in Firefox 50.1.0
* Operating System and version (desktop or mobile): Kubuntu 16.10

**Comment by tkusienicki** [comment]
It happens also when you change a page (table pagination).
