### ISSUE TITLE
hx.sort.compare treats `undefined` and `null` as normal strings

### ISSUE THREAD

**Issue by jonthans** [ocadotechnology/hexagonjs#372]
## Context

using hx.sort.compare to compare strings with undefined or null values
## Expected Behavior

```js
hx.sort.compare("m", null)
// 1

hx.sort.compare("o", null)
// 1

hx.sort.compare("t", undefined)
// 1

hx.sort.compare("v", undefined)
// 1

hx.sort.compare(null, undefined)
// 0

hx.sort.compare(undefined, null)
// 0
```
I'd mainly expect `undefined` or `null` values to be compared consistently and not according to their string representation. Whether or not the comparison of a defined value with `undefined` or `null` returns -1 or 1 is up for debate.
The last two examples may be debatable as well, if you want to prioritise one over the other.
## Actual Behavior

```js
hx.sort.compare("m", null)
// -1

hx.sort.compare("o", null)
// 1

hx.sort.compare("t", undefined)
// -1 

hx.sort.compare("v", undefined)
// 1

hx.sort.compare(null, undefined)
// -1

hx.sort.compare(undefined, null)
// 1
```
## Possible Fix

Check for whether or not each value is defined in the comparison.
## Steps to Reproduce

1. go to https://www.hexagonjs.io/
2. run above commands in the browser console

## Your Environment

* Hexagon Version: 1.9.0
* Browser Name and version: Chromium 55.0.2883.87, Firefox 50.1.0
* Operating System and version (desktop or mobile): Ubuntu 16.04 (64-bit)

**Comment by c-frater** [comment]
When using native `Array::sort`, `undefined` values are never passed to `hx.sort.compare`, however `null` values are:

```js
['z', undefined].sort(hx.sort.compare)
// ["z", undefined]

['z', null].sort(hx.sort.compare)
// [null, "z"]
```

This produces the same behaviour as native sorting:
```js
['z', undefined].sort()
// ["z", undefined]

['z', null].sort()
// [null, "z"]
```

From the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-sortcompare), `undefined` values are explicitly _not_ passed to the compare function:
```
1. If x and y are both undefined, return +0.
2. If x is undefined, return 1.
3. If y is undefined, return −1.
4. If the argument comparefn is not undefined, then
...
```

If we make this change, we should behave as the spec suggests:
> Because non-existent property values always compare greater than `undefined` property values, and `undefined` always compares greater than any other value, `undefined` property values always sort to the end of the result, followed by non-existent property values.

From my understanding, this would result in:
```js
hx.sort.compare(undefined, undefined)
// 0

hx.sort.compare(undefined, _)
// 1

hx.sort.compare(_, undefined)
// -1

hx.sort.compare(null, null)
// 0

hx.sort.compare(null, _)
// 1

hx.sort.compare(_, null)
// -1

[null, undefined, 'a', null, 'nil', undefined ,'undr', undefined, null, 'z', 'b'].sort(hx.sort.compare)
// ["a", "b", "nil", "undr", "z", null, null, null, undefined, undefined, undefined]
```

This is contrary to how the native sort would perform:
```js
[null, undefined, 'a', null, 'nil', undefined ,'undr', undefined, null, 'z', 'b'].sort()
// ["a", "b", "nil", null, null, null, "undr", "z", undefined, undefined, undefined]
```

We possibly only want to handle `undefined` values in the same way as they are done in the native `Array::sort` function and leave `null` values to behave as they do currently (as this would not cause `[..].sort(hx.sort.compare)` to change). 

If we were to add the `null` behaviour, I would suggest doing it as part of a Major release (or under a separate function? e.g. `hx.sort.nullCompare`)

**Comment by jonthans** [comment]
Having a separate compare function to keep the current behaviour consistent sounds good. I'd suggest calling it `hx.sort.compareNullsLast`.
So there are effectively two things to do then:
1. adjust the comparison behaviour for `undefined` to always compare greater
2. add a function that treats `nulls` (almost) like `undefined`
