### ISSUE TITLE
Dropdown uses node.html

### ISSUE THREAD

**Issue by jonthans** [ocadotechnology/hexagonjs#374]
Even the docs say that Dropdowns allow for html strings to be inserted as content into Dropdowns and the code actually calls `.html` with the provided string.
That functionality exposes a potentially big XSS vulnerability, especially when user-generated strings are inserted.

## Expected Behavior

Any string content string provided should be treated as a plain string instead of html.

## Actual Behavior

Dropdowns call `.html` on render with the provided string

## Possible Fix

use `hx.select(node).text(textContent)`

## Your Environment

* Hexagon Version: 1.9.0
* Browser Name and version: Chromium 55.0.2883.87, Firefox 50.1.0
* Operating System and version (desktop or mobile): Ubuntu 16.04 (64-bit)

**Comment by jmsmyth** [comment]
I think the best that can be done for the 1.x.x series of releases is adding a warning (maybe to `Selection::html` as well)

In 2.0.0 we should just remove `Selection::html` altogether.

**Comment by c-frater** [comment]
This will be resolved in #375
