### ISSUE TITLE
Selection: Deprecate Selection::html

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#375]
If used incorrectly, it can increase the chance of adding xss vulnerabilities. So probably best to remove it from the api

**Comment by georgesimms** [comment]
You should also investigate places where html strings are passed as parameters eg deprecate the Dropdown constructor that uses it.

**Comment by georgesimms** [comment]
Modules that currently seem to use Selection::html -
* Dropdown
* Paginator  (can trivially be replaced with fluid icons)
* Sidebar (ditto)
* Tree

Several tests also use the html getter. Maybe we can get away with just deprecating the setter ?

**Comment by georgesimms** [comment]
Do we also want to deprecate hx.parseHTML for the same reason ?

**Comment by jmsmyth** [comment]
Yes, I think so
