### ISSUE TITLE
Testing: Tests fail when run with Firefox or Chrome

### ISSUE THREAD

**Issue by jonthans** [ocadotechnology/hexagonjs#382]
## Context

Some of the tests (mainly autocomplete-picker) fail when run with Firefox or Chrome
## Expected Behavior

All tests should pass independent of the browser they are run in
## Actual Behavior

failing tests are listed below:
```
  autocomplete-picker
    autocomplete-picker
      ✖ should focus the input when picker is opened
      ✖ should clear the input value when the dropdown is opened
      ✖ should filter items when typing
      ✖ should not do anything when enter is pressed and the input is empty
      ✖ should not select an item when the key pressed is not enter
      ✖ should select the first item when enter is pressed and a value is entered
      ✖ should show the "No Results Found" text when no values are found
      ✖ should not select the first item when enter is pressed and a value is entered if the value is "No Results"
      ✖ should show other results correctly
      events:
        ✖ should emit the dropdown events with the "dropdown." prefix
        ✖ should emit the "change" event when the value is changed
  data-table
    data-table
      render
        maxWidth:
          ✖ should set the max width for individual columns
      option combinations
        compact
          ✖ should toggle the control panel visibility when the toggle is clicked
      events:
        filterchange
          ✖ should emit an event when filter changed with cause: user
```
## Steps to Reproduce
in `build/main/karma.js` change line 151 to `cfg.browsers = ['Firefox', 'Chrome']`
then run `node build/main/test.js` (alternatively, the call can be prefixed with `xvfb-run` if installed to avoid the browser window popping up)

## Your Environment

* Hexagon Version: current master
* Browser Name and version: Firefox 50.1.0, Chromium 55.0.2883.87
* Operating System and version (desktop or mobile): Ubuntu 16.04 (64 bit)

**Comment by c-frater** [comment]
The tests on master have been updated and tested and confirmed working in the following browsers:
- IE11
- Edge
- Chrome 
- Firefox
- Safari
- iOS Safari
- iOS Chrome
- Android Chrome
