### ISSUE TITLE
Data Table / filter - reset of the caret position 

### ISSUE THREAD

**Issue by tkusienicki** [ocadotechnology/hexagonjs#386]
## Steps to Reproduce
1. Go to https://www.hexagonjs.io/docs/1.10.0/data-table/
2. Click at the data table filter
3. Write `abcd`
4. Move the caret at the beginning
5. Write `1234`

## Expected Behavior
`1234abcd`

## Actual Behavior
`1abcd234`

## Your Environment
* Hexagon Version: `1.10.1`
* Browser Name and version: `Chrome 55.0.2883.95` & `Safari 10.0.3` (works fine on `Firefox`)
* Operating System and version: `OSX El Capitan 10.11.6`

**Comment by georgesimms** [comment]
It seems the root cause of it is this line:

```js
selection.select('.hx-data-table-filter').classed('hx-data-table-filter-visible', options.filterEnabled && !advancedSearchVisibleAndEnabled).value(this.filter());
```

IE typing in the filter box triggers a re-render, which triggers the filter value being set, which also moves the caret to the end.

The most straightforward solution would be not to reset the value if the new value would be the same as the old one
