### ISSUE TITLE
Components: Standardize cleanup

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#398]
## Context

hx.AutocompletePicker internally uses hx.Menu which uses hx.Dropdown, but doesn't expose hx.Dropdown's cleanup method which could lead to a memory leak because of runaway creation of (eg) clickdetectors.

All components that transitively use another component that needs cleanup should also expose a way to clean it up. It should also be straightforward to run that cleanup as soon as the element for the component is removed from the document.

**Comment by c-frater** [comment]
This is something to discuss in #476 - Closing this ticket to reduce clutter in the backlog
