### ISSUE TITLE
Titlebar: add fluid api

### ISSUE THREAD

**Issue by jmsmyth** [ocadotechnology/hexagonjs#399]
I'm finding that I have to copy this function into most new projects that use a titlebar:

```
export default function titleBar ({title, subtitle}) {
  return hx.div('hx-heading')
    .add(hx.div('hx-titlebar')
      .add(hx.div('hx-titlebar-container')
        .add(hx.div('hx-titlebar-header')
          .add(hx.detached('a').class('hx-titlebar-icon').attr('href', '/')
            .add(hx.detached('img').class('hx-logo')))
          .add(hx.div('hx-titlebar-title').text(title))
          .add(hx.div('hx-titlebar-subtitle').text(subtitle)))))
}
```

**Comment by c-frater** [comment]
I have a html template that's essentially equivalent to copying that function so I'm definitely all for adding this.

It would be awesome to also add an api for adding/removing/setting the links, icons and the 'custom area' (e.g. the 5th/6th example on [hexagonjs.io](https://www.hexagonjs.io/docs/titlebar/))

**Comment by jmsmyth** [comment]
Yeah, agreed it would be good to have links / icons / 'the custom area' - not sure how to go about adding them... maybe by passing in selections? Any ideas?

**Comment by c-frater** [comment]
I'd suggest for links / icons use a tag-input style method for adding? (possibly with a 'renderer'?)

For the custom area, I'd suggest working the same way the dropdown content works would be reasonable (e.g. accepts a selection or a function that populates)
