### ISSUE TITLE
Tag Input/Autocomplete: objects as items does not work

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#405]
## Context

When using objects with `{name, type}` properties in the autocomplete data, the value is set to `[object Object]`.

## Expected Behavior

The value should use the `inputMap` result

## Actual Behavior

It shows `[object Object]`

## Workaround
This detects when the new item that has been added is an object, removes it and replaces it with an inputMapped value.
```js
tagInput.on('add', ({value, type}) => {
  if (hx.isObject(value)) {
    const newItems = tagInput.items()
    newItems.pop()
    newItems.push(inputMap(value))
    tagInput.items(newItems)
  }
})
```

## Steps to Reproduce

```js
const items = [
  {
    type: 'A',
    name: 'A Text'
  },
  {
    type: 'B',
    name: 'B Text'
  },
  {
    type: 'D',
    name: 'D Text'
  },
  {
    type: 'C',
    name: 'C Text'
  }
]

const inputMap = ({name}) => name

const ti = hx.tagInput({
    autocompleteOptions: {
      renderer: (elem, item) => {
        hx.select(elem).text(item.type)
      },
      inputMap: inputMap
    },
    autocompleteData: (term, cb) => {
      cb(items.filter(({name}) => name.indexOf(term) > -1))
    }
  })

hx.select('body')
  .append(ti)
```

## Your Environment

* Hexagon Version: 1.11.0

**Comment by dzheleznyakov** [comment]
It could be useful to add this info to the docs: https://www.hexagonjs.io/docs/tag-input/
