### ISSUE TITLE
Modal: The modal itself should be passed into its setup function

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#41]
Often I have to do awkward things like

    modal = new hx.Modal node, (n) -> setup n, -> modal

To access the modal within its own setup function.

**Comment by jmsmyth** [comment]
The `this` in the setup function is the modal, ie:

    new hx.Modal('Title', function(n){
      setup(n, this)
    })

As you say, it is probably better to add it to the setup function as an extra param anyway. This would make it clearer in the docs and would make it possible to use es6 arrow functions for the setup func.

**Comment by c-frater** [comment]
This was fixed in #58
