### ISSUE TITLE
hx.isArray(): doesn't support multiple contexts

### ISSUE THREAD

**Issue by Crispy2** [ocadotechnology/hexagonjs#416]
## Context
The hx.isArray() function produces incorrect results when used within frames or windows.

## Expected Behavior
The function should return true if a valid array is passed in.

## Actual Behavior
The function returns false if an array is passed in that was created in a different context.

## Possible Fix
Use Array.isArray() instead of instanceof Array.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

## Your Environment
* Hexagon Version: 1.12.0
* Browser Name and version: Chrome 61.0.3163.100 (64-bit)
* Operating System and version (desktop or mobile): Windows 8 (desktop)

**Comment by jmsmyth** [comment]
Will be fixed in the next release
