### ISSUE TITLE
Event data documentation

### ISSUE THREAD

**Issue by greenjoe** [ocadotechnology/hexagonjs#42]
I've noticed that while the documentation lists all the events and describes when they are emitted it doesn't describe what the actual event object passed to the handler as an argument contain. 

I haven't checked all the modules but examples of those that do not contain event data information are: Data Table, Date Picker, Number picker, Picker, Inline Editable. 

The only way to see what is passed to the handler is to manually try and log it to console. I think it would be great to improve the documentation so that it is not needed.

**Comment by andersschuller** [comment]
I think this is the same issue as ocadotechnology/hexagonjs-site#8. The properties of the events are documented (for example [here](https://github.com/ocadotechnology/hexagonjs-site/blob/b1577bd8cd1d0eed4ec13800c19924cf9163960f/content/modules/data-table/versions/0.15.2.um#L12-L17) for Data Table), but they aren't being rendered by quantum.

**Comment by c-frater** [comment]
Closing - see #8 for progress
