### ISSUE TITLE
The requirements of the ease function are not clear

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#43]
The documentation suggests a custom ease can be used, but doesn't set out requirements for it, eg

* continuous
* monotonic
* ease(0) is 0
* ease(1) is 1
* ease([0, 1]) is a subset of [0, 1]  (implied by combinations of the above?)

**Comment by c-frater** [comment]
I'm not sure where the documentation you're referencing is located, what module is it in?

**Comment by c-frater** [comment]
@georgesimms I'm not sure where the documentation you're referencing is located, what module is it in?

**Comment by c-frater** [comment]
ocadotechnology/hexagonjs-site#57
