### ISSUE TITLE
hx.Form::component is undocumented

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#44]
Is this unintended for public use? We use it to listen to changes in a picker and modify the default value of a text input accordingly, for instance.

Alternatively, picker events could be piped to the form, ideally prefixed with the picker name.

**Comment by c-frater** [comment]
It's something we missed when documenting changes to the form builder. 

Also, issues related to missing or incorrect docs should be raised in the hexagonjs-site project as they are not issues with hexagonjs.

Moving to https://github.com/ocadotechnology/hexagonjs-site/issues/24
