### ISSUE TITLE
Deprecate hx.morph.register

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#45]
It is oddly singleton-y and global and could potentially lead to an issue where people accidentally overwrite one another's morphs (as they are not namespaced).

Also the Morphs module is a bit odd as it does stuff with global side effects merely by being included. Rather it should expose an object -

Eg

```
morph.then('fadeout', 100)
```

becomes

```
morph.then(hx.morphs.fadeout, 100)
```

This would also facilitate the documentaction of said module

**Comment by c-frater** [comment]
Duplicated by #450 - Closing this in favour of the new issue for tracking
