### ISSUE TITLE
Accept a template parameter for Modal

### ISSUE THREAD

**Issue by hosamaly** [ocadotechnology/hexagonjs#47]
Modal is currently too restrictive. It would be nice if I could pass a DOM object that contains a template for the modal body. This way I can construct custom modals.

**Comment by hosamaly** [comment]
I can see now it's in the constructor. Thanks.

**Comment by hosamaly** [comment]
But it doesn't exist for {{Modal.dialog}}. Do you think it's worth adding?

**Comment by c-frater** [comment]
The idea with `hx.modal.dialog` is to create a simple wrapper around the default modal that gives a modal with a title, message and some buttons to select. 
Generally, this should cover most popup dialogs and for those that it doesn't cover, a standard `hx.Modal` can be created with custom content so I don't think it should be added to `hx.modal.dialog` as well.
