### ISSUE TITLE
Dropdown: initial positioning sometimes displays incorrectly

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#550]
## Context

When opening a dropdown for the first time it sometimes displays in an incorrect position.

## Steps to Reproduce

Unable to reliably reproduce, except with some screenshot testing (which is difficult to debug)

## Your Environment

* Hexagon Version: 2.4.2

**Comment by p-koscielniak** [comment]
Hi
This issue is caused by using ```position: absolute; bottom: **px``` instead of ```position: absolute; top: **px``` for dropdown positioning.

`bottom`  positioning shouldn't be used because resizing window or changing viewport orientation changes dropdown position. 

Removing:
```
    if direction is 'up'
      yPos = 'bottom'
      y = document.body.clientHeight - y - dropdownRect.height
```
fixes flaky BackstopJS tests.
