### ISSUE TITLE
Date Picker: investigate view error

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#61]
From Travis Build log:
`WARN: 'view enter fn returned', <div class="hx-grid"></div>, '! It didn't match selector', '.hx-grid-row-heading', ', so you may encounter odd behavior'`

Identified as a result of #57

**Comment by georgesimms** [comment]
There's definitely something iffy going on here in hexagon...


      element.view('.hx-grid-row-heading')
      .enter (d) ->
        @classed('hx-grid-row-heading', true)
        node = @append('div').class('hx-grid')
        node.node()
      .update (d) -> @text(d).node()
      .apply(datepicker.localiser.localiseWeek())

So it says that the view is over `.hx-grid-row-heading` but it sets the *root* element to have that class, (multiple times!), not the child.

**Comment by georgesimms** [comment]
I wonder whether it should be

    element.classed 'hx-grid-row-heading', true
      .view '.hx-grid'
      .update (d) -> @text('d').node()
      .apply datepicker.localiser.localiseWeek()

... then you can use the default view enter fn, and you should get similar behavior if you are not calling apply multiple times on the same view
