### ISSUE TITLE
Data Table: grouped headings don't show in mobile mode.

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#65]

**Comment by georgesimms** [comment]
Consider the following:

    table.feed(hx.dataTable.objectFeed({
      headers: [
        { name: 'Name', id: 'name', groups: ['a'] },
        { name: 'Age', id: 'age', groups: ['a'] },
        { name: 'Profession', id: 'profession', groups: ['b'] }
      ],
      rows: [
        {
          id: 0, // hidden details can go here (not in the cells object)
          cells: { 'name': 'Bob', 'age': 25, 'profession': 'Developer' }
        },
        {
          id: 1,
          cells: { 'name': 'Jan', 'age': 41, 'profession': 'Artist' }
        },
        {
          id: 2,
          cells: { 'name': 'Dan', 'age': 41, 'profession': 'Builder' }
        }
      ]
    }))

![screenshot from 2015-12-24 11 13 19](https://cloud.githubusercontent.com/assets/7927477/11993988/89946fc0-aa2f-11e5-89e0-8c64ed4318ca.png)
![screenshot from 2015-12-24 11 13 31](https://cloud.githubusercontent.com/assets/7927477/11993991/8cd5a136-aa2f-11e5-84c4-fa1ba9d1c76e.png)

**Comment by c-frater** [comment]
Any suggestions for how this could be achieved?

**Comment by georgesimms** [comment]
Join on ': ' maybe?

Eg
```
a: Name Bob
a: Age 25
b: Profession Builder
```

**Comment by c-frater** [comment]
That makes sense, however I think that would look odd for multi level grouping and will make the columns wider than necessary.

Also, this would need to be a change to the header cell renderer as otherwise it forces something that isn't always suitable.

The following function would produce the structure above, this already works and gives you the desired structure.
```js
headerCellRenderer = function (e, cell) {
  var elem = hx.select(e)
  if (elem.classed('hx-data-table-cell-key')) {
    var groups = cell.groups.filter(function (d) { return d && d.length }).join(': ')
    elem.text(groups + ': ' + cell.name)
  } else {
    elem.text(cell.name)
  }
}
```

**Comment by c-frater** [comment]
Thinking about this some more after conversation with @georgesimms, it definitely makes sense to have an additional variable passed to the renderer as a boolean indicating whether the cell is a table header or a compact 'key' and changing the default headerCellRenderer to append the groups (as per the code snippet in the previous comment)
