### ISSUE TITLE
Selection: Add API for treating selections immutably

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#71]
As part of the shift towards doing more stuff with detached selections, this would be nice.

Eg a Selection would expose a "withStyle" method that instead of returning the same selection with the style applied, instead returned a new, detached selection that was otherwise identical to the previous one but with the new style applied. In the same vein one can have withAttached, withAdded, withClass, withHtml, withText and so on.

The challenge here is what to do about the hexagon-element-data-object and any event handlers the element has - these aren't necessarily cloneable. In the first instance they might want to be ignored.

**Comment by jmsmyth** [comment]
Wouldn't cloning like this come with a substantial performance hit?

**Comment by jmsmyth** [comment]
I'm not sure if we should do this. Happy for me to close?

**Comment by c-frater** [comment]
I agree, I think if you want to clone something you already can and it would most definitely be a large performance hit - The only thing you currently lose is events but I'd assume they'd be lost anyway?

**Comment by c-frater** [comment]
Not sure why this wasn't closed - we're still not planning to add this due to the performance hit
