### ISSUE TITLE
hx.Tree: the hideDisabledButtons parameter doesn't seem to have any effect

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#94]

**Comment by c-frater** [comment]
The disabled buttons are shown when at least one child has children of it's own, making all the text line up. Setting this to true hides the buttons. A screenshot of each case can be seen below

`hideDisabledButtons: false`:

![screen shot 2016-01-08 at 09 21 19](https://cloud.githubusercontent.com/assets/3194349/12194616/43da9d2c-b5e9-11e5-85a5-aa9869610e39.png)


`hideDisabledButtons: true`:

![screen shot 2016-01-08 at 09 21 43](https://cloud.githubusercontent.com/assets/3194349/12194617/43db1950-b5e9-11e5-81a3-f18bbdbde6f0.png)
