### ISSUE TITLE
hx.Tree: the disabled chevrons are too pale

### ISSUE THREAD

**Issue by georgesimms** [ocadotechnology/hexagonjs#95]
This issue may be theme-specific

When skim-reading the page, you don't notice the disabled chevrons unless you are looking for them

**Comment by c-frater** [comment]
They are quite pale, however the intention of disabled elements is to not draw attention to themselves so if this does need changing it shouldn't make them stand out more than text on the page.

**Comment by jmsmyth** [comment]
I agree with Charlie; the idea is that you shouldn't really notice them - if they were given more contrast they could be mistaken for being clickable. I'm not sure that anything should be changed here
